name: CI

on:
  push:
    branches: [main, work]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.1.8
      - name: Install dependencies
        run: bun install
      - name: Lint
        run: bunx eslint .
      - name: Run tests
        run: bun test
